# When main branch is updated:
# - Build
# - Deploy the artifacts to Maven Central
# - Update the dependency graph
name: Maven Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    uses: metricshub/workflows/.github/workflows/maven-central-deploy.yml@e601a107f80707d7bc39918a63ecad47f6f4fc65 # Maven 3.9.16
    with:
      jdkVersion: "17"
    secrets: inherit
